#!/bin/sh
ew="echo -e -n"
er="echo -e"
boo="\033[1m"
gry="\033[1;30m"
ylw="\033[1;33m"
no="\033[0m"
a="         ${gry}#####		"
b="        ${gry}#######		"
c="        ${gry}##${no}0${gry}#${no}0${gry}##		"
d="        ${gry}#${ylw}#####${gry}#		"
e="      ${gry}##${no}##${ylw}###${no}##${gry}##	"
f="     ${gry}#${no}##########${gry}##	"
g="    ${gry}#${no}############${gry}##	"
h="    ${gry}#${no}############${gry}###"
i="   ${ylw}##${gry}#${no}###########${gry}##${ylw}#"
j=" ${ylw}######${gry}#${no}#######${gry}#${ylw}######"
k=" #######${gry}#${no}#####${gry}#${ylw}#######"
l="   #####${gry}#######${ylw}#####${no}"

$ew "$a"
$ew "${boo}OS$no	"
sed -n '1p' /etc/os-release | awk -F= '{gsub(/"/, "", $2); print $2}'

$ew "$b"
$ew "${boo}KERNEL$no	"
uname -rm

$ew "$c"
$ew "${boo}CPU$no	"
grep -m 1 -w "model name" /proc/cpuinfo | cut -d':' -f2 | sed 's/.//'

$ew "$d"
$ew "${boo}UPTIME$no	"
uptime | sed -E 's/^[^,]*up *//; s/, *[[:digit:]]* users.*//; s/ hours,/h/ ; s/ min/m/; s/([[:digit:]]+):0?([[:digit:]]+)/\1h \2m/'

$ew "$e"
$ew "${boo}MEM$no	"
free -h | grep Mem | awk '{print $3}'

$ew "$f"
$ew "${boo}DISK$no	"
df -h | grep -w "/" | awk '{print $3" / "$4}'

$ew "$g"
$ew "${boo}SHELL$no	"
$er $SHELL

$er "$h"
$er "$i"
$er "$j"
$er "$k"
$er "$l"
